services:
  backend:
    build:
      context: ./backend
    image: wbd_backend
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SOLR_URL=http://solr:8983/solr
    depends_on:
      - redis
      - solr
    networks:
      - wbdnet

  frontend:
    build:
      context: ./frontend
    image: wbd_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - wbdnet

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - wbdnet

  solr:
    image: solr
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - mycore
    networks:
      - wbdnet

networks:
  wbdnet:

