name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        env:
          REDIS_URL: redis://localhost:6379
          SOLR_URL: http://localhost:8983/solr
        run: |
          cd backend
          npm test

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Start containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for services to initialize
        run: sleep 10

      - name: Check container status
        run: docker-compose ps

      - name: Test backend health (optional)
        run: |
          curl -f http://localhost:5000 || (echo "Backend not responding" && exit 1)

      - name: Test frontend health (optional)
        run: |
          curl -f http://localhost:3000 || (echo "Frontend not responding" && exit 1)

      - name: Shut down containers
        if: always()
        run: docker-compose down