name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

      solr:
        image: solr
        ports:
          - 8983:8983
        options: >-
          --health-cmd="curl --fail http://localhost:8983/solr/admin/ping || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run tests
        env:
          REDIS_URL: redis://localhost:6379
          SOLR_URL: http://localhost:8983/solr
        run: |
          cd backend
          npm test
          
      - name: Frotend tests
        run: |
          cd frontend
          npm install
          npm test
